=== Andrej235/ets-zemun/src/assets/json-data/schemas/profile.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 10,
      "description": "Name of the profile"
    },
    "description": {
      "type": "string",
      "minLength": 50,
      "description": "Full description of the profile"
    },
    "imagePath": {
      "type": "string",
      "pattern": "^/images/profiles/[^/]+\\.(jpg|jpeg|png|gif|bmp|webp|tiff|svg)$",
      "description": "Path to the image of the profile\nMUST start with ''@images/profiles/''\nMUST end with one of the following extensions: .jpg, .jpeg, .png, .gif, .bmp, .webp, .tiff, .svg\nThe referenced image MUST exist in the '/public/images/profiles/' folder",
      "default": "/images/profiles/default.png",
      "minLength": 20
    },
    "classes": {
      "type": "object",
      "properties": {
        "general": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "default": "default-class",
                "minLength": 1,
                "description": "Name of the class"
              },
              "perWeek": {
                "type": "array",
                "items": {
                  "type": "number",
                  "minimum": 0
                },
                "minItems": 4,
                "maxItems": 4,
                "description": "Weekly count\nFirst element cooresponds to first year, second element cooresponds to second year, third element cooresponds to third year, fourth element cooresponds to fourth year"
              }
            },
            "minLength": 1,
            "required": ["name", "perWeek"],
            "additionalProperties": false
          }
        },
        "specific": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "default": "default-class",
                "minLength": 1,
                "description": "Name of the class"
              },
              "perWeek": {
                "type": "array",
                "items": {
                  "type": "number",
                  "minimum": 0
                },
                "minItems": 4,
                "maxItems": 4,
                "description": "Weekly count\nFirst element cooresponds to first year, second element cooresponds to second year, third element cooresponds to third year, fourth element cooresponds to fourth year"
              }
            },
            "minLength": 1,
            "required": ["name", "perWeek"],
            "additionalProperties": false
          }
        }
      },
      "required": ["general", "specific"],
      "additionalProperties": false
    }
  },
  "required": ["name", "description", "imagePath", "classes"],
  "additionalProperties": false
}

=== Andrej235/ets-zemun/src/assets/json-data/data/profiles/elektrotehničar-informacionih-tehnologija.json
{
  "name": "Elektrotehničar informacionih tehnologija",
  "description": "Elektrotehničar informacionih tehnologija je obrazovni profil koji priprema učenike za rad u oblasti IT industrije. Fokusira se na razvoj softverskih aplikacija, kreiranje baza podataka, kao i dizajn i implementaciju statičkih i dinamičkih web stranica. Učenici se takođe osposobljavaju za održavanje i zaštitu informacionih sistema, što ih čini konkurentnim na tržištu rada u sektoru tehnologije i digitalnih rešenja.",
  "imagePath": "/images/profiles/elektrotehnicar-informacionih-tehnologija.png",
  "classes": {
    "general": [
      {
        "name": "Srpski jezik i književnost",
        "perWeek": [3, 3, 3, 3]
      },
      {
        "name": "Engleski jezik",
        "perWeek": [2, 2, 2, 2]
      },
      {
        "name": "Fizičko vaspitanje",
        "perWeek": [2, 2, 2, 2]
      },
      {
        "name": "Matematika",
        "perWeek": [3, 3, 3, 3]
      },
      {
        "name": "Računarstvo i informatika",
        "perWeek": [2, 0, 0, 0]
      },
      {
        "name": "Istorija",
        "perWeek": [2, 0, 0, 0]
      },
      {
        "name": "Geografija",
        "perWeek": [2, 0, 0, 0]
      },
      {
        "name": "Hemija",
        "perWeek": [2, 0, 0, 0]
      },
      {
        "name": "Likovna kultura",
        "perWeek": [1, 0, 0, 0]
      },
      {
        "name": "Biologija",
        "perWeek": [0, 2, 0, 0]
      },
      {
        "name": "Sociologija sa pravima građana",
        "perWeek": [0, 0, 2, 0]
      },
      {
        "name": "Veronauka",
        "perWeek": [1, 1, 1, 1]
      },
      {
        "name": "Građansko vaspitanje",
        "perWeek": [1, 1, 1, 1]
      }
    ],
    "specific": [
      {
        "name": "Fizika",
        "perWeek": [2, 2, 0, 0]
      },
      {
        "name": "Osnove elektrotehnike",
        "perWeek": [4, 4, 0, 0]
      },
      {
        "name": "Programiranje",
        "perWeek": [2, 4, 3, 3]
      },
      {
        "name": "Računarska grafika i multimedija",
        "perWeek": [2, 0, 0, 0]
      },
      {
        "name": "Elektronika",
        "perWeek": [0, 4, 0, 0]
      },
      {
        "name": "Veb dizajn",
        "perWeek": [0, 2, 0, 0]
      },
      {
        "name": "Baze podataka",
        "perWeek": [0, 3, 2, 0]
      },
      {
        "name": "Računarski sistemi",
        "perWeek": [0, 0, 3, 0]
      },
      {
        "name": "Veb programiranje",
        "perWeek": [0, 0, 3, 3]
      },
      {
        "name": "Računari u sistemima upravljanja",
        "perWeek": [0, 0, 2, 0]
      },
      {
        "name": "Računarske mreže i internet servisi",
        "perWeek": [0, 0, 0, 3]
      },
      {
        "name": "Zaštita informacionih sistema",
        "perWeek": [0, 0, 0, 2]
      },
      {
        "name": "Primenjene informacione tehnologije",
        "perWeek": [0, 0, 6, 6]
      },
      {
        "name": "Preduzetništvo",
        "perWeek": [0, 0, 0, 2]
      },
      {
        "name": "Elektronsko poslovanje",
        "perWeek": [0, 0, 0, 2]
      },
      {
        "name": "Praktična nastava",
        "perWeek": [2, 0, 0, 0]
      },
      {
        "name": "Izborni predmeti",
        "perWeek": [0, 0, 2, 2]
      }
    ]
  }
}

=== Andrej235/ets-zemun/apps/website/src/assets/json-data/data/profiles/elektromehaničar-za-rashladne-i-termičke-uredjaje.json
{
  "name": "Elektromehaničar za rashladne i termičke uređaje",
  "description": "Elektromehaničar za rashladne i termičke uređaje obučava učenike za rad sa različitim vrstama rashladnih i klimatskih uređaja, kao i za montažu, održavanje i popravku ovih sistema. Učenici stiču znanja o električnim instalacijama, termalnim procesima i uređajima koji koriste termalne i rashladne sisteme. Ovaj profil pruža praktične veštine za rad u industriji, domaćinstvima i servisima za klimatizaciju i hlađenje.",
  "imagePath": "/images/profiles/elektromehanicar-za-rashladne-i-termicke-uredjaje.jpg",
  "classes": {
    "general": [],
    "specific": []
  }
}

=== Andrej235/ets-zemun/apps/website/src/assets/json-data/data/profiles/elektrotehničar-automatike.json
{
  "name": "Elektrotehničar automatike",
  "description": "Elektrotehničar automatike je profil koji priprema učenike za rad sa automatizovanim sistemima u industriji. Učenici stiču znanje o projektovanju, održavanju i nadzoru industrijskih automatizovanih sistema, upravljanju mašinama i robotima, kao i kontroli proizvodnih procesa. Ovaj smer je ključan za industrije koje se bave proizvodnjom, energetikom i drugim oblastima gde je potrebna visoka preciznost i efikasnost u radu.",
  "imagePath": "/images/profiles/elektrotehnicar-automatike.png",
  "classes": {
    "general": [],
    "specific": []
  }
}
